services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: demo-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demo_spring
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pstgrs
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_DB: demo_spring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pstgrs
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
    driver: bridge